### PR TITLE
Make the DigitalOcean instructions a bit more clear.

### PR DESCRIPTION
**Pull request by kevincox**
Mostly putting the `./install` with the `-d` flag to make it clear where to use it.

### CODE REVIEW

**Comment by jeaye** [comment]
I don't like this change, as it currently stands. If you just want to specify that `-d` goes with `./install`, sure, but you also removed one of the most important bits: telling people to look at the `-h` for help.

**Comment by kevincox** [comment]
Yeah, that's a bit controversial. It just seemed unrelated to that section and was discussed elsewhere where it felt more appropriate. I can add it back in if you prefer.

**Comment by jeaye** [comment]
Yes please; people are going to skip through a lot of the readme to the Digital Ocean section; I want to make sure it's clear that there's a `-h` option, no matter how much they skip.

**Comment by kevincox** [comment]
:+1: I'll update tonight.

**Comment by kevincox** [comment]
Updated.

**Comment by jeaye** [comment]
None of the sections have a new line after the header, but you added one here. You're welcome to remove it yourself; if not, I will after merging; my OCD wouldn't let me sleep otherwise. :)

**Comment by kevincox** [comment]
Oops, I added that to rewrap the section. Sorry about that, it is fixed now.

**Comment by jeaye** [comment]
Thank you very much for the PR and for understanding my nitpicking.

**Pull request merged**
